import type { NextPage } from 'next'
import Head from 'next/head'

import Nav from '../components/Nav'



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chamling Cycles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />


        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&family=Tapestry&display=swap" rel="stylesheet"/> 
     </Head>

<div className='homepage'>

<Nav/>
  

</div>
    </div>
  )
}

export default Home
