import type { NextPage } from 'next'
import Head from 'next/head'

import Nav from '../components/Nav'

import Slider from '../components/Slider';
import Newarrivals from '../components/Newarrivals';
import Bestseller from '../components/Bestseller';
import Trendingnow from '../components/Trendingnow';
import Footer from '../components/Footer';
import Superfooter from '../components/Superfooter';






const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chamling Cycles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />


        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Bungee&family=Fira+Sans+Condensed&family=Roboto:wght@300&family=Tapestry&display=swap" rel="stylesheet"/> 
     </Head>

<div className='homepage'>

<Nav/>
<Slider/>
<Newarrivals/>

<Bestseller/>
<Trendingnow/>


<Footer/>
{/* <Superfooter/> */}
</div>
    </div>
  )
}

export default Home
